# Generated by Django 4.2.2 on 2023-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planlanan Tarih'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='low', max_length=20, verbose_name='Öncelik'),
        ),
    ]
