# Generated by Django 4.2.2 on 2023-07-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_planned_date_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(default='BK', editable=False, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Urgency Level', 'Urgency Level'), ('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='low', max_length=20, verbose_name='Öncelik'),
        ),
    ]
