# Generated by Django 4.2.2 on 2023-07-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_task_number_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
    ]
